import { adminDatabases, DB } from "@/lib/portal";
import { requireStaff } from "@/lib/staff";
import { Query } from "node-appwrite";

export const dynamic = "force-dynamic";
export default async function Withdrawals({ searchParams }: { searchParams: Promise<{ result?: string }> }) {
  await requireStaff("withdrawals");
  const { result } = await searchParams;
  const records = (await adminDatabases().listDocuments({ databaseId: DB, collectionId: "member_requests", queries: [Query.orderDesc("$createdAt"),Query.limit(100)] })).documents;
  return <><h1 className="text-3xl font-bold">Withdrawal requests</h1><p className="mt-2 text-slate-600">Verify the member, available funds and payout details outside this screen before deciding. Approving here only updates status; it does not send money.</p>{result && <p role={result === "saved" ? "status" : "alert"} className="mt-5 rounded-lg bg-blue-50 p-3">{result === "saved" ? "Decision recorded and visible to the member." : "Decision could not be saved. Refresh and try again."}</p>}<div className="mt-7 space-y-5">{records.map(r => <article key={r.$id} className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">UGX {Number(r.amount).toLocaleString("en-UG")}</h2><p className="text-sm text-slate-600">Member ID: {String(r.userId)} · {new Date(r.$createdAt).toLocaleString("en-UG")}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-sm capitalize">{String(r.status)}</span></div><p className="mt-4 text-sm"><strong>Payment method:</strong> {String(r.method)}</p><p className="mt-1 whitespace-pre-wrap text-sm"><strong>Details:</strong> {String(r.details)}</p>{r.decisionNote && <p className="mt-2 text-sm"><strong>Staff note:</strong> {String(r.decisionNote)}</p>}{r.status === "pending" && <form className="mt-5 flex flex-wrap items-end gap-3" action="/api/staff/withdrawals" method="post"><input type="hidden" name="id" value={r.$id} /><label className="flex-1 text-sm font-medium">Decision note<input required maxLength={500} name="note" className="mt-1 w-full rounded-lg border p-2" placeholder="Verification or rejection reason" /></label><button name="status" value="approved" className="rounded-lg bg-green-700 px-4 py-2 text-white">Approve</button><button name="status" value="rejected" className="rounded-lg bg-red-700 px-4 py-2 text-white">Reject</button></form>}</article>)}{!records.length && <p className="rounded-xl bg-white p-6">No requests yet.</p>}</div></>;
}
